### ISSUE TITLE
could you please make the document for installing and using it

### ISSUE THREAD

**Issue by alochym01** [ddurdle/GoogleDrive-VideoStream#2]
there is no document for install and using it
please spend somtime to make a documents for them

thank you

**Comment by qazero** [comment]
Any update regarding this?

**Comment by ddurdle** [comment]
Sorry, no ETA

**Comment by haxunivil** [comment]
Simple and reliable script for generating HTML5 video streaming links from Google Drive files.
it's not a proxy script, provide links direct to Google’s Video CDN
Easy Installation, You just need PHP hosting and Google Cloud PHP App account thats all, now you are ready to fly.
It's work with all public google drive videos on free and gsuite accounts.

Buy Google Drive Stream Links Script and TEST IT:
https://google.driveplayer.stream/

**Comment by ddurdle** [comment]
I've created a python service that will service google drive (public content ).  Works with VLC and other media streaming devices to playback content stored with public shareable link.  This essentially acts as a CDN that will service content delivery using a static URL and bypassing any virus scanning checks.  It will redeliver content using a reusable and public URL, so your maximum number of downloads of a particular file should not occur.

https://github.com/ddurdle/Python-GoogleDrive-StaticLinks

**Comment by ddurdle** [comment]
This has been replaced by:

https://github.com/ddurdle/Python-GoogleDrive-VideoStream
